xc16-v1.70
From XC16_v1.70.src.zip (sha1 de65699c4410c26e136dd2c018612bbbf3b23ddd)

Removed files:
 src/XC_GCC/binutils/bfd/doc/bfd.info
 src/XC_GCC/binutils/binutils/doc/binutils.info
 src/XC_GCC/binutils/binutils/sysroff.info
 src/XC_GCC/binutils/etc/configure.info
 src/XC_GCC/binutils/etc/standards.info
 src/XC_GCC/binutils/gas/doc/as.info
 src/XC_GCC/binutils/gprof/gprof.info
 src/XC_GCC/binutils/ld/ld.info
 src/XC_GCC/checkout.out
 src/XC_GCC/cloog/doc/cloog.info
 src/XC_GCC/gcc/mpc/doc/mpc.info
 src/XC_GCC/gcc/mpfr/autom4te.cache/output.0
 src/XC_GCC/gcc/mpfr/autom4te.cache/requests
 src/XC_GCC/gcc/mpfr/autom4te.cache/traces.0
 src/XC_GCC/gcc/mpfr/mpfr.info
 src/XC_GCC/gmp/doc/gmp.info
 src/XC_GCC/gmp/doc/gmp.info-1
 src/XC_GCC/gmp/doc/gmp.info-2
 src/XC_GCC/libelf/autom4te.cache/output.0
 src/XC_GCC/libelf/autom4te.cache/requests
 src/XC_GCC/libelf/autom4te.cache/traces.0
 src/XC_GCC/ppl/autom4te.cache/output.0
 src/XC_GCC/ppl/autom4te.cache/requests
 src/XC_GCC/ppl/autom4te.cache/traces.0
 src/XC_GCC/.XC_GCC.info
 src/XC_GCC/zlib/libz.a
 src/XC_GCC/zlib/Makefile
 src/XC_GCC/zlib/zconf.h
 src/acme/.acme.info
 src/acme/bfd/doc/bfd.info
 src/acme/bfd/doc/bfd.info-1
 src/acme/bfd/doc/bfd.info-2
 src/acme/bfd/doc/bfd.info-3
 src/acme/bfd/doc/bfd.info-4
 src/acme/bfd/doc/bfd.info-5
 src/acme/bfd/doc/bfd.info-6
 src/acme/bfd/doc/bfd.info-7
 src/acme/bfd/doc/bfd.info-8
 src/acme/bfd/doc/bfd.info-9
 src/acme/binutils/doc/binutils.info
 src/acme/binutils/doc/binutils.info-1
 src/acme/binutils/doc/binutils.info-2
 src/acme/binutils/doc/binutils.info-3
 src/acme/binutils/sysroff.info
 src/acme/checkout.out
 src/acme/etc/configure.info
 src/acme/etc/configure.info-1
 src/acme/etc/configure.info-2
 src/acme/etc/configure.info-3
 src/acme/etc/standards.info
 src/acme/gas/doc/as.info
 src/acme/gas/doc/as.info-1
 src/acme/gas/doc/as.info-10
 src/acme/gas/doc/as.info-11
 src/acme/gas/doc/as.info-12
 src/acme/gas/doc/as.info-2
 src/acme/gas/doc/as.info-3
 src/acme/gas/doc/as.info-4
 src/acme/gas/doc/as.info-5
 src/acme/gas/doc/as.info-6
 src/acme/gas/doc/as.info-7
 src/acme/gas/doc/as.info-8
 src/acme/gas/doc/as.info-9
 src/acme/gdb/doc/gdb.info
 src/acme/gdb/doc/gdb.info-1
 src/acme/gdb/doc/gdb.info-10
 src/acme/gdb/doc/gdb.info-11
 src/acme/gdb/doc/gdb.info-12
 src/acme/gdb/doc/gdb.info-13
 src/acme/gdb/doc/gdb.info-2
 src/acme/gdb/doc/gdb.info-3
 src/acme/gdb/doc/gdb.info-4
 src/acme/gdb/doc/gdb.info-5
 src/acme/gdb/doc/gdb.info-6
 src/acme/gdb/doc/gdb.info-7
 src/acme/gdb/doc/gdb.info-8
 src/acme/gdb/doc/gdb.info-9
 src/acme/gdb/doc/gdbint.info
 src/acme/gdb/doc/gdbint.info-1
 src/acme/gdb/doc/gdbint.info-2
 src/acme/gdb/doc/gdbint.info-3
 src/acme/gdb/doc/stabs.info
 src/acme/gdb/doc/stabs.info-1
 src/acme/gdb/doc/stabs.info-2
 src/acme/gdb/doc/stabs.info-3
 src/acme/gdb/doc/stabs.info-4
 src/acme/gprof/gprof.info
 src/acme/gprof/gprof.info-1
 src/acme/gprof/gprof.info-2
 src/acme/gprof/gprof.info-3
 src/acme/ld/ld.info
 src/acme/ld/ld.info-1
 src/acme/ld/ld.info-2
 src/acme/ld/ld.info-3
 src/acme/ld/ld.info-4
 src/acme/ld/ld.info-5
 src/acme/ld/ld.info-6
 src/c30_resource/src/c30/c30_device.info

diff --git a/build_XC16_451 b/build_XC16_451
--- a/build_XC16_451
+++ b/build_XC16_451
@@ -23,6 +23,7 @@ BUILD64=0
 export ABI=32
 
 BUGURL="https://www.microchip.com/technical-support"
+BUILD="expat gmp cloog libelf zlib"
 
 # What is the native host?
 export NATIVE=
@@ -126,8 +127,8 @@ if [ "$INSTALL" != "" ]; then
   INSTALL_DIR="${INSTALL}-${TARGET_OS}${SUFFIX}"
 fi
 
-if [ "$BUILD" = "" ]; then
-  BUILD="expat gmp cloog libelf zlib gcc"
+if ( ! echo $BUILD | grep -q "g++" ); then
+  BUILD="$BUILD gcc"
 fi
 
 if [ -f $SRC_DIR/../c30_resource/src/c30/resource_info.h ]; then
@@ -388,9 +389,43 @@ mkdir -p gcc
   echo "}"
 
   CXXFLAGS="$EXTRA_CFLAGS $OPT" GCC_FOR_TARGET='pic30-gcc' CC_FOR_TARGET='pic30-gcc' AS_FOR_TARGET=$PIC30_CD/bin/pic30-as LD_FOR_TARGET=$PIC30_CD/bin/pic30-ld CFLAGS="$EXTRA_CFLAGS $OPT -DLONG_MODIFIER -D_BUILD_C30_ -D_BUILD_MCHP_ ${EXTRA_OPTS} ${EXTRA_DEFINES}" $SRC_DIR/gcc/configure ${CROSS} ${BUILD_OPTION} --target=pic30-$OMF $LTO --disable-threads --disable-libmudflap --disable-libssp --disable-libstdcxx-pch --disable-hosted-libstdcxx --with-gnu-as --with-gnu-ld --enable-languages=c --disable-nls --disable-libgomp --without-headers --disable-libffi --disable-bootstrap --prefix=${INSTALL}/bin --libexecdir=${INSTALL}/bin --program-prefix=pic30- --with-libelf=${WORKING_DIR}/host-libs/ $DWARF --with-gmp=$WORKING_DIR/host-libs --with-ppl=$WORKING_DIR/host-libs --with-cloog=$WORKING_DIR/host-libs --with-zlib=$WORKING_DIR/host-libs --with-bugurl="${BUGURL}" --with-host-libstdcxx="$STATIC"
-
-
   
+  make 
+  )
+fi
+
+
+if ( echo $BUILD | grep -q -i g++ ); then
+echo
+echo "*********** G++"
+echo 
+
+mkdir -p gcc
+(
+  cd gcc
+
+  if [ -d $C30_RESOURCE_DIR ]; then
+    EXTRA_OPTS="$EXTRA_OPTS -I $C30_RESOURCE_DIR"
+  else
+    echo "***** cannot find c30_resource"
+    exit 1
+  fi
+
+  case $SUFFIX in
+    "-nolm") ;;
+  esac
+
+  DWARF=""
+  if [ "$OMF" = "elf" ]; then
+    DWARF="--with-dwarf2"
+  fi
+
+  echo "{"
+  echo "  CXXFLAGS=\"$EXTRA_CFLAGS $OPT\" GCC_FOR_TARGET='pic30-gcc' CC_FOR_TARGET='pic30-gcc' AS_FOR_TARGET=$PIC30_CD/bin/pic30-as LD_FOR_TARGET=$PIC30_CD/bin/pic30-ld CFLAGS=\"$EXTRA_CFLAGS $OPT -DLONG_MODIFIER -D_BUILD_C30_ -D_BUILD_MCHP_ ${EXTRA_OPTS} ${EXTRA_DEFINES}\" $SRC_DIR/gcc/configure ${CROSS} ${BUILD_OPTION} --enable-coverage --target=pic30-$OMF $LTO --disable-threads --disable-libmudflap --disable-libssp --disable-libstdcxx-pch --disable-hosted-libstdcxx --with-gnu-as --with-gnu-ld --enable-languages=c,c++ --disable-nls --disable-libgomp --without-headers --disable-libffi --disable-bootstrap --prefix=${INSTALL}/bin --libexecdir=${INSTALL}/bin --program-prefix=pic30- --with-libelf=${WORKING_DIR}/host-libs/ $DWARF --with-gmp=$WORKING_DIR/host-libs --with-ppl=$WORKING_DIR/host-libs --with-cloog=$WORKING_DIR/host-libs --with-zlib=$WORKING_DIR/host-libs --with-bugurl=\"${BUGURL}\" --with-host-libstdcxx=\"$STATIC\" "
+  echo "}"
+
+  CXXFLAGS="$EXTRA_CFLAGS $OPT" GCC_FOR_TARGET='pic30-gcc' CC_FOR_TARGET='pic30-gcc' AS_FOR_TARGET=$PIC30_CD/bin/pic30-as LD_FOR_TARGET=$PIC30_CD/bin/pic30-ld CFLAGS="$EXTRA_CFLAGS $OPT -DLONG_MODIFIER -D_BUILD_C30_ -D_BUILD_MCHP_ ${EXTRA_OPTS} ${EXTRA_DEFINES}" $SRC_DIR/gcc/configure ${CROSS} ${BUILD_OPTION} --target=pic30-$OMF $LTO --disable-threads --disable-libmudflap --disable-libssp --disable-libstdcxx-pch --disable-hosted-libstdcxx --with-gnu-as --with-gnu-ld --enable-languages=c,c++ --disable-nls --disable-libgomp --without-headers --disable-libffi --disable-bootstrap --prefix=${INSTALL}/bin --libexecdir=${INSTALL}/bin --program-prefix=pic30- --with-libelf=${WORKING_DIR}/host-libs/ $DWARF --with-gmp=$WORKING_DIR/host-libs --with-ppl=$WORKING_DIR/host-libs --with-cloog=$WORKING_DIR/host-libs --with-zlib=$WORKING_DIR/host-libs --with-bugurl="${BUGURL}" --with-host-libstdcxx="$STATIC"
+
   make 
   )
 fi
@@ -414,8 +449,16 @@ if [ "$INSTALL_DIR" != "" ]; then
     cp -v gcc/gcc/xgcc${EXE}  $INSTALL_DIR/bin/bin/$OMF-gcc${EXE}
   fi
 
+  if [ -f gcc/gcc/g++${EXE} ]; then
+    cp -v gcc/gcc/g++${EXE}  $INSTALL_DIR/bin/bin/$OMF-g++${EXE}
+  fi
+
   if [ -f gcc/gcc/cc1${EXE} ]; then
     cp -v gcc/gcc/cc1${EXE}  $INSTALL_DIR/bin/bin/$OMF-cc1${EXE}
+  fi
+
+  if [ -f gcc/gcc/cc1plus${EXE} ]; then
+    cp -v gcc/gcc/cc1plus${EXE}  $INSTALL_DIR/bin/bin/$OMF-cc1plus${EXE}
   fi
 
   if [ -f gcc/gcc/cpp${EXE} ]; then
