xc16-v1.26
From MPLAB XC16 v1.26.src.zip (sha1 88264d55a78cb8d5c13180c3baa4c2bf661c3c2d)

Removed files:
 src/XC_GCC/.XC_GCC.info
 src/XC_GCC/binutils/bfd/doc/bfd.info
 src/XC_GCC/binutils/binutils/doc/binutils.info
 src/XC_GCC/binutils/etc/configure.info
 src/XC_GCC/binutils/etc/standards.info
 src/XC_GCC/binutils/gas/doc/as.info
 src/XC_GCC/binutils/gprof/gprof.info
 src/XC_GCC/binutils/ld/ld.info
 src/XC_GCC/checkout.out
 src/XC_GCC/cloog/doc/cloog.info
 src/XC_GCC/gcc/mpc/doc/mpc.info
 src/XC_GCC/gcc/mpfr/mpfr.info
 src/XC_GCC/gmp/doc/gmp.info
 src/XC_GCC/gmp/doc/gmp.info-1
 src/XC_GCC/gmp/doc/gmp.info-2
 src/XC_GCC/libelf/autom4te.cache/output.0
 src/XC_GCC/libelf/autom4te.cache/requests
 src/XC_GCC/libelf/autom4te.cache/traces.0
 src/XC_GCC/zlib/Makefile
 src/XC_GCC/zlib/libz.a
 src/XC_GCC/zlib/zconf.h
 src/acme/.acme.info
 src/acme/bfd/doc/bfd.info
 src/acme/bfd/doc/bfd.info-1
 src/acme/bfd/doc/bfd.info-2
 src/acme/binutils/doc/binutils.info
 src/acme/binutils/doc/binutils.info-1
 src/acme/binutils/doc/binutils.info-2
 src/acme/checkout.out
 src/acme/etc/configure.info
 src/acme/etc/configure.info-1
 src/acme/etc/configure.info-2
 src/acme/etc/standards.info
 src/acme/gas/doc/as.info
 src/acme/gas/doc/as.info-1
 src/acme/gas/doc/as.info-2
 src/acme/gprof/gprof.info
 src/acme/gprof/gprof.info-1
 src/acme/gprof/gprof.info-2
 src/acme/ld/ld.info
 src/acme/ld/ld.info-1
 src/acme/ld/ld.info-2
 src/acme/ld/testsuite/ld-pic30-elf32/unit-tests/WACA/test.out

diff --git a/build_XC16_451 b/build_XC16_451
--- a/build_XC16_451
+++ b/build_XC16_451
@@ -10,12 +10,13 @@ OMF=elf
 TARGET_OS=native
 UNAME=`uname -s | sed -e 's/[^a-zA-Z].*$//' | tr "[:upper:]" "[:lower:]"`
 BUILD_OS="i386-$UNAME"
-EXTRA_DEFINES=
+EXTRA_DEFINES="-DRESOURCE_MISMATCH_OK"
 EXTRA_OPTS=
 CROSS=
 STATIC=
 BUILD_SHA=
 INSTALL_DIR=  
+XCLM_DIR=
 
 BUGURL="http://www.microchip.com/support"
 
@@ -98,9 +99,9 @@ while [ "$DONE" = "0" ]; do
          echo "    -build=<module>"
          echo "    -D  specify extra defines for build"
          echo
-         exit;;
+         exit 1;;
       *) echo "Unknown option $1";
-         exit;;
+         exit 1;;
     esac
   fi
 done
@@ -148,7 +149,7 @@ if [ "$BUILD_SHA" = "1" ]; then
    BUILT_SHA=`${TMP:-/tmp}/build_sha $INSTALL_DIR/xclm/install/client/bin/xclm${EXE_SUFFIX} 2>&1`
    if ( echo $BUILT_SHA | grep -q -i "Error:" ); then
       echo "$BUILT_SHA"
-      exit
+      exit 1
    fi
    BUILD_SHA="-DMCHP_XCLM_SHA256_DIGEST_VAL=$BUILT_SHA"
 fi
@@ -268,6 +269,18 @@ mkdir -p zlib
 )
 fi
 
+if [ $SUFFIX == "-xclm" ] || [ $SUFFIX == "-exlm" ]; then
+  XCLM_DIR=`find $SRC_DIR/../ -iname xclm_public.h -exec dirname {} \;`
+  if [ ! -f $XCLM_DIR/xclm_public.h ]; then
+    echo "**** cannot find dir containing xclm_public.h"
+    exit 1
+  fi
+  XCLM_DIR="-I $XCLM_DIR"
+else
+  echo "**** not building with XCLM"
+fi
+
+  
 if ( echo $BUILD | grep -q -i gcc ); then
 echo
 echo "*********** GCC"
@@ -281,7 +294,7 @@ mkdir -p gcc
     EXTRA_OPTS="$EXTRA_OPTS -I $C30_RESOURCE_DIR"
   else
     echo "***** cannot find c30_resource"
-    exit
+    exit 1
   fi
 
   case $SUFFIX in
@@ -294,7 +307,7 @@ mkdir -p gcc
   fi
 
   echo "{"
-  echo "  CXXFLAGS=\"$EXTRA_CFLAGS $OPT\" GCC_FOR_TARGET='pic30-gcc' CC_FOR_TARGET='pic30-gcc' AS_FOR_TARGET=$PIC30_CD/bin/pic30-as LD_FOR_TARGET=$PIC30_CD/bin/pic30-ld CFLAGS=\"$EXTRA_CFLAGS $OPT -D_BUILD_C30_ -D_BUILD_MCHP_ ${EXTRA_OPTS} ${EXTRA_DEFINES}\" $SRC_DIR/gcc/configure --build=${BUILD_OS} ${CROSS} --target=pic30-$OMF $LTO --disable-threads --disable-libmudflap --disable-libssp --disable-libstdcxx-pch --disable-hosted-libstdcxx --with-gnu-as --with-gnu-ld --enable-languages=c --disable-nls --disable-libgomp --without-headers --disable-libffi --disable-bootstrap --prefix=${INSTALL}/bin --libexecdir=${INSTALL}/bin --program-prefix=pic30- --with-libelf=${WORKING_DIR}/host-libs/ $DWARF --with-gmp=$WORKING_DIR/host-libs --with-ppl=$WORKING_DIR/host-libs --with-cloog=$WORKING_DIR/host-libs --with-zlib=$WORKING_DIR/host-libs --with-bugurl=\"${BUGURL}\" --with-host-libstdcxx=\"$STATIC\" "
+  echo "  CXXFLAGS=\"$EXTRA_CFLAGS $OPT\" GCC_FOR_TARGET='pic30-gcc' CC_FOR_TARGET='pic30-gcc' AS_FOR_TARGET=$PIC30_CD/bin/pic30-as LD_FOR_TARGET=$PIC30_CD/bin/pic30-ld CFLAGS=\"$EXTRA_CFLAGS $OPT -D_BUILD_C30_ -D_BUILD_MCHP_ ${EXTRA_OPTS} ${EXTRA_DEFINES}\" $SRC_DIR/gcc/configure --build=${BUILD_OS} ${CROSS} --enable-coverage --target=pic30-$OMF $LTO --disable-threads --disable-libmudflap --disable-libssp --disable-libstdcxx-pch --disable-hosted-libstdcxx --with-gnu-as --with-gnu-ld --enable-languages=c --disable-nls --disable-libgomp --without-headers --disable-libffi --disable-bootstrap --prefix=${INSTALL}/bin --libexecdir=${INSTALL}/bin --program-prefix=pic30- --with-libelf=${WORKING_DIR}/host-libs/ $DWARF --with-gmp=$WORKING_DIR/host-libs --with-ppl=$WORKING_DIR/host-libs --with-cloog=$WORKING_DIR/host-libs --with-zlib=$WORKING_DIR/host-libs --with-bugurl=\"${BUGURL}\" --with-host-libstdcxx=\"$STATIC\" "
   echo "}"
 
   CXXFLAGS="$EXTRA_CFLAGS $OPT" GCC_FOR_TARGET='pic30-gcc' CC_FOR_TARGET='pic30-gcc' AS_FOR_TARGET=$PIC30_CD/bin/pic30-as LD_FOR_TARGET=$PIC30_CD/bin/pic30-ld CFLAGS="$EXTRA_CFLAGS $OPT -D_BUILD_C30_ -D_BUILD_MCHP_ ${EXTRA_OPTS} ${EXTRA_DEFINES}" $SRC_DIR/gcc/configure --build=${BUILD_OS} ${CROSS} --target=pic30-$OMF $LTO --disable-threads --disable-libmudflap --disable-libssp --disable-libstdcxx-pch --disable-hosted-libstdcxx --with-gnu-as --with-gnu-ld --enable-languages=c --disable-nls --disable-libgomp --without-headers --disable-libffi --disable-bootstrap --prefix=${INSTALL}/bin --libexecdir=${INSTALL}/bin --program-prefix=pic30- --with-libelf=${WORKING_DIR}/host-libs/ $DWARF --with-gmp=$WORKING_DIR/host-libs --with-ppl=$WORKING_DIR/host-libs --with-cloog=$WORKING_DIR/host-libs --with-zlib=$WORKING_DIR/host-libs --with-bugurl="${BUGURL}" --with-host-libstdcxx="$STATIC"
